// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pos_app;

namespace pos_app.Migrations
{
    [DbContext(typeof(POSDbContext))]
    [Migration("20190421014935_ReportsMigration")]
    partial class ReportsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("pos_app.Models.Department", b =>
                {
                    b.Property<int>("DeptID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeptTitle");

                    b.Property<int>("ProdID");

                    b.HasKey("DeptID");

                    b.HasIndex("ProdID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("pos_app.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DepartmentDeptID");

                    b.Property<string>("Description");

                    b.Property<string>("Price");

                    b.Property<int>("Quantity");

                    b.Property<string>("Title");

                    b.HasKey("ProductID");

                    b.HasIndex("DepartmentDeptID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("pos_app.Models.Report", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ReportTitle");

                    b.HasKey("RID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("pos_app.Models.User", b =>
                {
                    b.Property<int>("UID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssignedRoleURID");

                    b.Property<int?>("ID");

                    b.Property<string>("Password");

                    b.HasKey("UID");

                    b.HasIndex("AssignedRoleURID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pos_app.Models.UserRole", b =>
                {
                    b.Property<int>("URID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleTitle");

                    b.HasKey("URID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("pos_app.Models.Department", b =>
                {
                    b.HasOne("pos_app.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProdID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pos_app.Models.Product", b =>
                {
                    b.HasOne("pos_app.Models.Department")
                        .WithMany("Products")
                        .HasForeignKey("DepartmentDeptID");
                });

            modelBuilder.Entity("pos_app.Models.User", b =>
                {
                    b.HasOne("pos_app.Models.UserRole", "AssignedRole")
                        .WithMany()
                        .HasForeignKey("AssignedRoleURID");
                });
#pragma warning restore 612, 618
        }
    }
}
